### PR TITLE
PR1

### PR DESCRIPTION
**Pull request by RobertPower**
Format Blogs

### CODE REVIEW

**Comment by nathanpower** [comment]
LGTM 👍 

Your first PR! 🎉 

Time to put _familiar with github and markdown_ on the old LinkedIn profile 😄

**Review by nathanpower — APPROVED** [review]

**Comment by RobertPower** [comment]
Whoop! That's a good idea in fairness! What's PR?

**Comment by nathanpower** [comment]
>Whoop! That's a good idea in fairness! What's PR?

[Pull Request](https://en.wikipedia.org/wiki/Distributed_version_control#Pull_requests), you can make one to any open-source project, or any repository you have access to.

**Comment by RobertPower** [comment]
Oh yes, very cool. I'm a coder now on tinder

**Pull request merged**
